services:
  # PostgreSQL database service
  postgredb:
    image: postgres:13 # Use a versão do PostgreSQL desejada
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - postgresvolume:/var/lib/postgresql/data


  app:
    depends_on:
      - postgredb
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/av3poo
    container_name: av3poo
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgredb:$POSTGRES_DOCKER_PORT/$POSTGRES_DB
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  postgresvolume: